spring:
  data:
    mongodb:
      auto-index-creation: true
      database: microservicescustomer

server:
  port: 9591

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9500/eureka
