server:
  port: 9591

spring:
  data:
    mongodb:
      auto-index-creation: true
      database: microservicescustomer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
