spring:
    data:
        mongodb:
            auto-index-creation: true
            database: microservicescredits

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
