eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      routes:
        - id: server-generated-encrypt
          uri: lb://server-generated-encrypt
          predicates:
            - Path=/service/generated/encrypt/**
          filters:
            - StripPrefix=2
        - id: microservices-customer
          uri: lb://microservices-customer
          predicates:
            - Path=/microservices/customer/**
          filters:
            - StripPrefix=2
