server:
  port: 9500

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        -id: microservices-customer
          uri: lb://microservices-customer
          predicates:
          - Path=/microservices/customer/**
          filters:
          - StripPrefix=2
